# Generated by Django 5.1.5 on 2025-08-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indexs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('desc', models.TextField()),
                ('desc_en', models.TextField(null=True)),
                ('desc_ru', models.TextField(null=True)),
                ('desc_uz', models.TextField(null=True)),
                ('about_name', models.CharField(max_length=255)),
                ('about_name_en', models.CharField(max_length=255, null=True)),
                ('about_name_ru', models.CharField(max_length=255, null=True)),
                ('about_name_uz', models.CharField(max_length=255, null=True)),
                ('about_desc', models.TextField()),
                ('about_desc_en', models.TextField(null=True)),
                ('about_desc_ru', models.TextField(null=True)),
                ('about_desc_uz', models.TextField(null=True)),
                ('service_name', models.CharField(max_length=255)),
                ('service_name_en', models.CharField(max_length=255, null=True)),
                ('service_name_ru', models.CharField(max_length=255, null=True)),
                ('service_name_uz', models.CharField(max_length=255, null=True)),
                ('service_desc', models.TextField()),
                ('service_desc_en', models.TextField(null=True)),
                ('service_desc_ru', models.TextField(null=True)),
                ('service_desc_uz', models.TextField(null=True)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='services')),
                ('project_name', models.CharField(max_length=255)),
                ('project_name_en', models.CharField(max_length=255, null=True)),
                ('project_name_ru', models.CharField(max_length=255, null=True)),
                ('project_name_uz', models.CharField(max_length=255, null=True)),
                ('project_desc', models.TextField()),
                ('project_desc_en', models.TextField(null=True)),
                ('project_desc_ru', models.TextField(null=True)),
                ('project_desc_uz', models.TextField(null=True)),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('project_link', models.URLField(blank=True, null=True, verbose_name='url')),
                ('team_name', models.CharField(max_length=255)),
                ('team_name_en', models.CharField(max_length=255, null=True)),
                ('team_name_ru', models.CharField(max_length=255, null=True)),
                ('team_name_uz', models.CharField(max_length=255, null=True)),
                ('team_jobs', models.CharField(max_length=100)),
                ('team_jobs_en', models.CharField(max_length=100, null=True)),
                ('team_jobs_ru', models.CharField(max_length=100, null=True)),
                ('team_jobs_uz', models.CharField(max_length=100, null=True)),
                ('team_image', models.ImageField(blank=True, null=True, upload_to='teams')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='telegram')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='linkedin')),
                ('insta', models.URLField(blank=True, null=True, verbose_name='insta')),
                ('custom_count', models.BigIntegerField(default=1)),
                ('project_count', models.BigIntegerField(default=1)),
                ('win_count', models.BigIntegerField(default=1)),
                ('works_count', models.BigIntegerField(default=1)),
            ],
        ),
    ]
