services:
  - type: web
    name: django-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Solar.settings
      - key: PYTHONUNBUFFERED
        value: "1"