# Generated by Django 5.2.6 on 2025-09-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_uz', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_kz', models.CharField(max_length=200, null=True)),
                ('name_tj', models.CharField(max_length=200, null=True)),
                ('name_tr', models.CharField(max_length=200, null=True)),
                ('desc', models.TextField()),
                ('desc_uz', models.TextField(null=True)),
                ('desc_en', models.TextField(null=True)),
                ('desc_kz', models.TextField(null=True)),
                ('desc_tj', models.TextField(null=True)),
                ('desc_tr', models.TextField(null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('adverb_name', models.CharField(max_length=200)),
                ('adverb_name_uz', models.CharField(max_length=200, null=True)),
                ('adverb_name_en', models.CharField(max_length=200, null=True)),
                ('adverb_name_kz', models.CharField(max_length=200, null=True)),
                ('adverb_name_tj', models.CharField(max_length=200, null=True)),
                ('adverb_name_tr', models.CharField(max_length=200, null=True)),
                ('adverb_desc', models.TextField()),
                ('adverb_desc_uz', models.TextField(null=True)),
                ('adverb_desc_en', models.TextField(null=True)),
                ('adverb_desc_kz', models.TextField(null=True)),
                ('adverb_desc_tj', models.TextField(null=True)),
                ('adverb_desc_tr', models.TextField(null=True)),
                ('adverb_more', models.CharField(max_length=50)),
                ('adverb_more_uz', models.CharField(max_length=50, null=True)),
                ('adverb_more_en', models.CharField(max_length=50, null=True)),
                ('adverb_more_kz', models.CharField(max_length=50, null=True)),
                ('adverb_more_tj', models.CharField(max_length=50, null=True)),
                ('adverb_more_tr', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
